# Copyright (c) 2023 ETH Zurich
#
# SPDX-License-Identifier: BSL-1.0
# Distributed under the Boost Software License, Version 1.0. (See accompanying
# file LICENSE_1_0.txt or copy at http://www.boost.org/LICENSE_1_0.txt)

name: Documentation

on:
  merge_group:
  pull_request:
    branches:
      # Development and release branches
      - main
      - release**
  push:
    branches:
      # Development and release branches
      - main
      - release**
      # Bors branches
      - trying
      - staging

jobs:
  build:
    name: github/documentation/build
    runs-on: ubuntu-latest
    container: pikaorg/pika-ci-base:17

    steps:
    - uses: actions/checkout@v3
    - name: Install sphinx and a theme
      run: pip install sphinx sphinx-material
    - name: Build documentation
      run: sphinx-build -W -n -a -b html docs build/docs
    - name: Upload HTML output as artifact
      uses: actions/upload-artifact@v3
      with:
        name: github-pages
        path: build/docs
        retention-days: 14
  deploy:
    name: github/documentation/deploy
    runs-on: ubuntu-latest
    needs: build
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy documentation to GitHub Pages
        uses: actions/deploy-pages@v2
        id: deployment
