# Copyright (c) 2020 EXASOL
#
# SPDX-License-Identifier: BSL-1.0
# Distributed under the Boost Software License, Version 1.0. (See accompanying
# file LICENSE_1_0.txt or copy at http://www.boost.org/LICENSE_1_0.txt)

name: Linux CI (asan/ubsan)

on:
  merge_group:
  pull_request:
  push:
    branches:
      # Development and release branches
      - main
      - release**
      # Bors branches
      - trying
      - staging

jobs:
  build:
    name: github/linux/asan_ubsan/fast
    # if: ${{ github.event_name == 'merge_group' }}
    runs-on: ubuntu-latest
    container: pikaorg/pika-ci-base:18

    steps:
    - uses: actions/checkout@v3
    - name: Update apt repositories for ccache
      run: apt update
    - name: Setup ccache
      uses: hendrikmuhs/ccache-action@v1.2
      with:
        key: linux-asan-ubsan
    - name: Configure
      shell: bash
      run: |
          cmake \
              . \
              -Bbuild \
              -GNinja \
              -DCMAKE_CXX_COMPILER_LAUNCHER=ccache \
              -DCMAKE_BUILD_TYPE=Debug \
              -DPIKA_WITH_UNITY_BUILD=ON \
              -DPIKA_WITH_MALLOC=system \
              -DPIKA_WITH_EXAMPLES=ON \
              -DPIKA_WITH_TESTS=ON \
              -DPIKA_WITH_TESTS_EXAMPLES=ON \
              -DPIKA_WITH_TESTS_EXTERNAL_BUILD=OFF \
              -DPIKA_WITH_TESTS_HEADERS=OFF \
              -DPIKA_WITH_TESTS_MAX_THREADS=2 \
              -DPIKA_WITH_COMPILER_WARNINGS=ON \
              -DPIKA_WITH_COMPILER_WARNINGS_AS_ERRORS=ON \
              -DPIKA_WITH_SANITIZERS=ON \
              -DCMAKE_CXX_FLAGS="-fsanitize=address -fsanitize=undefined -fno-omit-frame-pointer" \
              -DPIKA_WITH_STACKOVERFLOW_DETECTION=OFF
    - name: Build
      shell: bash
      run: |
          cmake --build build --target tests.examples
    - name: Test
      shell: bash
      run: |
          export ASAN_OPTIONS=fast_unwind_on_malloc=0
          export LSAN_OPTIONS=suppressions=$PWD/tools/asan.supp
          export UBSAN_OPTIONS=print_stacktrace=1,suppressions=$PWD/tools/ubsan.supp
          cd build
          ctest \
            --timeout 120 \
            --output-on-failure \
            --tests-regex tests.examples
